// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dfsqcviqgubwkuntwppt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmc3FjdmlxZ3Vid2t1bnR3cHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNjI5NjQsImV4cCI6MjA3OTczODk2NH0.VdOG4x1hs7_zZi2Zy10MYZdEVQNf2utPANgShjmMb6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);